#!/usr/bin/env python

import json
from subprocess import check_output, call
from os import path

datecmd = 'date'
if path.exists('/usr/local/bin/gdate'):
  datecmd = '/usr/local/bin/gdate'

outfile = 'mongoexportlocal_' + check_output(datecmd + ' --rfc-3339=seconds', shell=True).strip().replace(' ', '_') + '.json'
login = json.load(open('mongologin.json'))
host = login['mongohost']
db = login['mongodb']
user = login['mongouser']
passwd = login['mongopassword']

call('mongoexport -h ' + host + ' -d ' + db + ' -u ' + user + ' -p ' + passwd + " -c logs -o '" + outfile + "'", shell=True)

